// Mocks generated by Mockito 5.4.6 from annotations
// in painel_windowns/test/admin/tabs/admin_locations_tab_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:painel_windowns/data/models/bssid_mapping.dart' as _i7;
import 'package:painel_windowns/data/models/unit_model.dart' as _i6;
import 'package:painel_windowns/services/auth_service.dart' as _i2;
import 'package:painel_windowns/services/device_service.dart' as _i5;
import 'package:painel_windowns/services/location_service.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i2.AuthService {
  MockAuthService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isLoggedIn =>
      (super.noSuchMethod(Invocation.getter(#isLoggedIn), returnValue: false)
          as bool);

  @override
  bool get isAdmin =>
      (super.noSuchMethod(Invocation.getter(#isAdmin), returnValue: false)
          as bool);

  @override
  _i3.Future<void> initializeFromStorage() =>
      (super.noSuchMethod(
            Invocation.method(#initializeFromStorage, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<Map<String, dynamic>> login(String? username, String? password) =>
      (super.noSuchMethod(
            Invocation.method(#login, [username, password]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> createUser(Map<String, dynamic>? userData) =>
      (super.noSuchMethod(
            Invocation.method(#createUser, [userData]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> updateUser(
    String? userId,
    Map<String, dynamic>? userData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUser, [userId, userData]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> getUsers() =>
      (super.noSuchMethod(
            Invocation.method(#getUsers, []),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> deleteUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUser, [userId]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<Map<String, dynamic>> changePassword(
    String? currentPassword,
    String? newPassword,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [currentPassword, newPassword]),
            returnValue: _i3.Future<Map<String, dynamic>>.value(
              <String, dynamic>{},
            ),
          )
          as _i3.Future<Map<String, dynamic>>);

  @override
  _i3.Future<void> logout() =>
      (super.noSuchMethod(
            Invocation.method(#logout, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i4.LocationService {
  MockLocationService() {
    _i1.throwOnMissingStub(this);
  }
}

/// A class which mocks [DeviceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDeviceService extends _i1.Mock implements _i5.DeviceService {
  MockDeviceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<dynamic>> fetchDevices(
    String? token,
    List<_i6.Unit>? units,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchDevices, [token, units]),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);

  @override
  _i3.Future<List<_i7.BssidMapping>> fetchBssidMappings(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBssidMappings, [token]),
            returnValue: _i3.Future<List<_i7.BssidMapping>>.value(
              <_i7.BssidMapping>[],
            ),
          )
          as _i3.Future<List<_i7.BssidMapping>>);

  @override
  _i3.Future<List<_i7.BssidMapping>> fetchBssidsForUnit(
    String? token,
    String? unitName,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchBssidsForUnit, [token, unitName]),
            returnValue: _i3.Future<List<_i7.BssidMapping>>.value(
              <_i7.BssidMapping>[],
            ),
          )
          as _i3.Future<List<_i7.BssidMapping>>);

  @override
  _i3.Future<String> sendCommand(
    String? token,
    String? serialNumber,
    String? command,
    Map<String, dynamic>? parameters,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#sendCommand, [
              token,
              serialNumber,
              command,
              parameters,
            ]),
            returnValue: _i3.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#sendCommand, [
                  token,
                  serialNumber,
                  command,
                  parameters,
                ]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> deleteDevice(String? token, String? serialNumber) =>
      (super.noSuchMethod(
            Invocation.method(#deleteDevice, [token, serialNumber]),
            returnValue: _i3.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#deleteDevice, [token, serialNumber]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> createUnit(String? token, _i6.Unit? unit) =>
      (super.noSuchMethod(
            Invocation.method(#createUnit, [token, unit]),
            returnValue: _i3.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#createUnit, [token, unit]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> updateUnit(
    String? token,
    String? unitName,
    _i6.Unit? unit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateUnit, [token, unitName, unit]),
            returnValue: _i3.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#updateUnit, [token, unitName, unit]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> deleteUnit(String? token, String? unitName) =>
      (super.noSuchMethod(
            Invocation.method(#deleteUnit, [token, unitName]),
            returnValue: _i3.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#deleteUnit, [token, unitName]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> createBssidMapping(
    String? token,
    _i7.BssidMapping? mapping,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createBssidMapping, [token, mapping]),
            returnValue: _i3.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#createBssidMapping, [token, mapping]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> updateBssidMapping(
    String? token,
    String? macAddressRadio,
    _i7.BssidMapping? mapping,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateBssidMapping, [
              token,
              macAddressRadio,
              mapping,
            ]),
            returnValue: _i3.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#updateBssidMapping, [
                  token,
                  macAddressRadio,
                  mapping,
                ]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> deleteBssidMapping(
    String? token,
    String? macAddressRadio,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteBssidMapping, [token, macAddressRadio]),
            returnValue: _i3.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#deleteBssidMapping, [
                  token,
                  macAddressRadio,
                ]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<_i6.Unit>> fetchUnits(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#fetchUnits, [token]),
            returnValue: _i3.Future<List<_i6.Unit>>.value(<_i6.Unit>[]),
          )
          as _i3.Future<List<_i6.Unit>>);

  @override
  _i3.Future<List<Map<String, dynamic>>> fetchLocationHistory(
    String? token,
    String? serialNumber,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#fetchLocationHistory, [token, serialNumber]),
            returnValue: _i3.Future<List<Map<String, dynamic>>>.value(
              <Map<String, dynamic>>[],
            ),
          )
          as _i3.Future<List<Map<String, dynamic>>>);

  @override
  _i3.Future<List<dynamic>> fetchTotems(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#fetchTotems, [token]),
            returnValue: _i3.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i3.Future<List<dynamic>>);
}
